const CONSTANT = {
  //ANCHOR - THEME CONSTANTS
  THEME_COLOR: '#fff',
  THEME_TEXT: '#008BD4',
  THEME_LABEL_COLOR: '#004A61',
  INPUT_COLOR: '#E6E8EB',
  PLACEHOLDER_COLOR: '#004a6190',
  MAIN_TEXT_COLOR: '#002140',
  CART_VIEW_COLOR: '#E3FDF4',
};

export default CONSTANT;
